// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoRE3YaU1kE1v08D6vNyhSz9x_jTy7le8',
    appId: '1:503346247957:web:6c6b23d7006c176ad4111c',
    messagingSenderId: '503346247957',
    projectId: 'cicddemo-cf4ec',
    authDomain: 'cicddemo-cf4ec.firebaseapp.com',
    storageBucket: 'cicddemo-cf4ec.firebasestorage.app',
    measurementId: 'G-NWT8EX3B43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCna5Z0RwBddMiy_bC0uLp4GIxmIeevPkQ',
    appId: '1:503346247957:android:63dd78d0688028b6d4111c',
    messagingSenderId: '503346247957',
    projectId: 'cicddemo-cf4ec',
    storageBucket: 'cicddemo-cf4ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSWjBRkwZGaYOvXixD0-pdVJJeMCDdLhg',
    appId: '1:503346247957:ios:c2d82b7e5aea2b50d4111c',
    messagingSenderId: '503346247957',
    projectId: 'cicddemo-cf4ec',
    storageBucket: 'cicddemo-cf4ec.firebasestorage.app',
    iosBundleId: 'com.example.cicddemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSWjBRkwZGaYOvXixD0-pdVJJeMCDdLhg',
    appId: '1:503346247957:ios:c2d82b7e5aea2b50d4111c',
    messagingSenderId: '503346247957',
    projectId: 'cicddemo-cf4ec',
    storageBucket: 'cicddemo-cf4ec.firebasestorage.app',
    iosBundleId: 'com.example.cicddemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoRE3YaU1kE1v08D6vNyhSz9x_jTy7le8',
    appId: '1:503346247957:web:2d752a95093407cbd4111c',
    messagingSenderId: '503346247957',
    projectId: 'cicddemo-cf4ec',
    authDomain: 'cicddemo-cf4ec.firebaseapp.com',
    storageBucket: 'cicddemo-cf4ec.firebasestorage.app',
    measurementId: 'G-1JHKYPXCF9',
  );
}
