name: Flutter Firebase App Distribution

on:
  push:
    branches:
      - main

jobs:
  distribute:
    name: Build & Upload APK
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.5"
          cache: true

      # Verify Flutter Version
      - name: Verify Flutter Version
        run: flutter --version

      # Cache Flutter packages
      - name: Cache Flutter Packages
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      # Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Flutter Analyze
      - name: Flutter Analyze
        run: flutter analyze

      # Read version from pubspec.yaml
      - name: Read App Version
        run: |
          VERSION_NAME=$(grep '^version:' pubspec.yaml | cut -d' ' -f2 | cut -d'+' -f1)

          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

          echo "Version Name : $VERSION_NAME"
          echo "Build Number : ${{ github.run_number }}"

      # Build Release APK
      - name: Build Release APK
        run: |
          flutter build apk \
            --release \
            --build-name=$VERSION_NAME \
            --build-number=$BUILD_NUMBER

      # Rename APK
      - name: Rename APK
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk \
             build/app/outputs/flutter-apk/cicddemo-v${VERSION_NAME}+${BUILD_NUMBER}.apk

      # Build Release AAB
      - name: Build Release AAB
        run: |
          flutter build appbundle \
            --release \
            --build-name=$VERSION_NAME \
            --build-number=$BUILD_NUMBER

      # Rename AAB
      - name: Rename AAB
        run: |
          mv build/app/outputs/bundle/release/app-release.aab \
             build/app/outputs/bundle/release/cicddemo-v${VERSION_NAME}+${BUILD_NUMBER}.aab

      # Upload APK Artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cicddemo-v${{ env.VERSION_NAME }}+${{ env.BUILD_NUMBER }}-apk
          path: build/app/outputs/flutter-apk/cicddemo-v${{ env.VERSION_NAME }}+${{ env.BUILD_NUMBER }}.apk
          retention-days: 7

      # Upload AAB Artifact
      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cicddemo-v${{ env.VERSION_NAME }}+${{ env.BUILD_NUMBER }}-aab
          path: build/app/outputs/bundle/release/cicddemo-v${{ env.VERSION_NAME }}+${{ env.BUILD_NUMBER }}.aab
          retention-days: 7

      # Upload APK to Firebase App Distribution
      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          groups: QA
          file: build/app/outputs/flutter-apk/cicddemo-v${{ env.VERSION_NAME }}+${{ env.BUILD_NUMBER }}.apk
          releaseNotes: |
            CI/CD Demo Build

            Version: ${{ env.VERSION_NAME }}
            Build: ${{ env.BUILD_NUMBER }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}